### ISSUE TITLE
We have found the following errors

### ISSUE THREAD

**Issue by serdarayalp** [wbstr/liferay-newsletter#1]
Hello, We have found the following errors

1 - Registered users do not get the Confirmation Email
2 - Unsubscribe does not work because the unsubscribe link in the newsletter is not correct. In the newsletter you get a link like

http://domainname.tld/web/guest/subscription?canckey=b06c055791cc11dfe66620019b1da30e

but it should be
http://domainname.tld/web/guest/subscription?canckey[]=b06c055791cc11dfe66620019b1da30e

**Comment by Psyhowcs** [comment]
Hello,
2. is fixed.

**Comment by serdarayalp** [comment]
Hello Webstar Team,

thanks for the corrections on the links (scribe and unscribe). The only problem is that the project cann't be reconstructed again mit Maven. 
We get the following error when we write "mvn clean install"

> mvn clean install

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] WcsNewsletter
[INFO] WcsNewsletter Portlet Service
[INFO] WcsNewsletter Portlet
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building WcsNewsletter 1.0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ WcsNewsletter ---
[INFO]
[INFO] --- license-maven-plugin:1.5:update-file-header (first) @ WcsNewsletter ---
[WARNING] No file to scan.
[INFO]
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ WcsNewsletter ---
[INFO] Installing D:\Liferay-Development\004-sdk611v4\Maven\liferay-newsletter-master\pom.xml to D:\Liferay-Development\apache-maven-repository\com\wcs\WcsNewsletter\1.0.0.1\WcsNewsletter-1.0.0.1.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building WcsNewsletter Portlet Service 1.0.0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.wcs:jsewcslib:jar:2.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.springframework:org.springframework.transaction:jar:3.1.0.RELEASE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WcsNewsletter ..................................... SUCCESS [0.939s]
[INFO] WcsNewsletter Portlet Service ..................... FAILURE [0.107s]
[INFO] WcsNewsletter Portlet ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.290s
[INFO] Finished at: Wed Oct 02 13:42:13 CEST 2013
[INFO] Final Memory: 7M/16M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project WcsNewsletter-portlet-service: Could not resolve dependencies for project com.wcs:WcsNewsletter-portlet-service:jar:1.0.0.1: The following artifacts could not
 be resolved: com.wcs:jsewcslib:jar:2.0-SNAPSHOT, org.springframework:org.springframework.transaction:jar:3.1.0.RELEASE: Could not find artifact com.wcs:jsewcslib:jar:2.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :WcsNewsletter-portlet-service

how can we solve the problems of package dependencies.

thxs a lot
Serdar Ayalp

**Comment by titiwcs** [comment]
dependency issue is fixed
